# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyone', '0002_auto_20171031_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, '保密')], default=1),
        ),
    ]
